package com.psl.training.enums;

public enum Category {
	ACTION,
	COMEDY,
	DRAMA,
	FANTASY,
	HORROR,
	MYSTERY,
	ROMANCE,
	THRILLER,
	COMEDY_DRAMA,
	CRIME_THRILLER,
	TECHNO_THRILLER,
	SCIENCE_FICTION,
	COMEDY_ROMANCE_DRAMA,
	ACTION_ADVENTURE,
	ROMANCE_DRAMA_THRILLER,
	COMEDY_ADVENTURE_ANIMATION;
}
